# Generated by Django 4.1.7 on 2023-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, verbose_name='ID')),
                ('area', models.IntegerField(choices=[(1, '#19'), (2, '#20'), (3, '#21'), (4, '#22')], verbose_name='网格')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('avatar', models.FileField(max_length=128, upload_to='bank/%Y/%m/%d/', verbose_name='头像')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('face_token', models.CharField(max_length=32, verbose_name='FaceToken')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
            ],
        ),
    ]
