# Generated by Django 4.1.7 on 2023-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='活动标题')),
                ('text', models.TextField(blank=True, null=True, verbose_name='活动描述')),
                ('date', models.DateField(verbose_name='活动日期')),
                ('count', models.IntegerField(default=0, verbose_name='报名人数')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
            ],
        ),
    ]
