# Generated by Django 4.1.7 on 2023-04-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_joinrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=128, upload_to='bank/%Y/%m/%d/', verbose_name='图片')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('price', models.IntegerField(default=0, verbose_name='积分')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='举办活动日期'),
        ),
    ]
