# Generated by Django 5.0.4 on 2024-04-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_goods_alter_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='任务具体信息')),
                ('avatar', models.FileField(max_length=128, upload_to='bank/%Y/%m/%d/', verbose_name='头像')),
                ('deadline', models.DateTimeField(verbose_name='任务截止时间')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='xxx',
            field=models.ManyToManyField(through='api.JoinRecord', to='api.userinfo', verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='joinrecord',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac', to='api.activity', verbose_name='活动'),
        ),
    ]
