# Generated by Django 5.0.4 on 2024-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_taskstext_activity_xxx_alter_joinrecord_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='area',
        ),
        migrations.AlterField(
            model_name='taskstext',
            name='avatar',
            field=models.FileField(max_length=128, null=True, upload_to='bank/%Y/%m/%d/', verbose_name='任务图片记录'),
        ),
        migrations.AlterField(
            model_name='taskstext',
            name='deadline',
            field=models.CharField(max_length=16, verbose_name='任务截止时间'),
        ),
    ]
